global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Service Discovery (Eureka)
  - job_name: 'service-discovery'
    static_configs:
      - targets: ['service-discovery:8761']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Main Backend Service
  - job_name: 'budgetwise-backend'
    static_configs:
      - targets: ['budgetwise-backend:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # AI Service
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Community Service
  - job_name: 'community-service'
    static_configs:
      - targets: ['community-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # MySQL
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']